name: My First Workflow

on:
  push:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "GitHub Actions  working!"
